// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `org.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.thanos.model.svc;

public class Brand implements java.lang.Cloneable,
                              java.io.Serializable
{
    public String applyDate;

    public String brand;

    public String name;

    public String registeredNo;

    public String category;

    public String status;

    public Brand()
    {
        this.applyDate = "";
        this.brand = "";
        this.name = "";
        this.registeredNo = "";
        this.category = "";
        this.status = "";
    }

    public Brand(String applyDate, String brand, String name, String registeredNo, String category, String status)
    {
        this.applyDate = applyDate;
        this.brand = brand;
        this.name = name;
        this.registeredNo = registeredNo;
        this.category = category;
        this.status = status;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Brand r = null;
        if(rhs instanceof Brand)
        {
            r = (Brand)rhs;
        }

        if(r != null)
        {
            if(this.applyDate != r.applyDate)
            {
                if(this.applyDate == null || r.applyDate == null || !this.applyDate.equals(r.applyDate))
                {
                    return false;
                }
            }
            if(this.brand != r.brand)
            {
                if(this.brand == null || r.brand == null || !this.brand.equals(r.brand))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.registeredNo != r.registeredNo)
            {
                if(this.registeredNo == null || r.registeredNo == null || !this.registeredNo.equals(r.registeredNo))
                {
                    return false;
                }
            }
            if(this.category != r.category)
            {
                if(this.category == null || r.category == null || !this.category.equals(r.category))
                {
                    return false;
                }
            }
            if(this.status != r.status)
            {
                if(this.status == null || r.status == null || !this.status.equals(r.status))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::svc::Brand");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, applyDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, brand);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, registeredNo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, category);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, status);
        return h_;
    }

    public Brand clone()
    {
        Brand c = null;
        try
        {
            c = (Brand)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.applyDate);
        ostr.writeString(this.brand);
        ostr.writeString(this.name);
        ostr.writeString(this.registeredNo);
        ostr.writeString(this.category);
        ostr.writeString(this.status);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.applyDate = istr.readString();
        this.brand = istr.readString();
        this.name = istr.readString();
        this.registeredNo = istr.readString();
        this.category = istr.readString();
        this.status = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Brand v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Brand ice_read(com.zeroc.Ice.InputStream istr)
    {
        Brand v = new Brand();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Brand> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Brand v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Brand> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Brand.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Brand _nullMarshalValue = new Brand();

    public static final long serialVersionUID = 865434759L;
}
