// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `org.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.thanos.model.svc;

public class Partner implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String name;

    public String rate;

    public String scc;

    public Partner()
    {
        this.name = "";
        this.rate = "";
        this.scc = "";
    }

    public Partner(String name, String rate, String scc)
    {
        this.name = name;
        this.rate = rate;
        this.scc = scc;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Partner r = null;
        if(rhs instanceof Partner)
        {
            r = (Partner)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.rate != r.rate)
            {
                if(this.rate == null || r.rate == null || !this.rate.equals(r.rate))
                {
                    return false;
                }
            }
            if(this.scc != r.scc)
            {
                if(this.scc == null || r.scc == null || !this.scc.equals(r.scc))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::svc::Partner");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, scc);
        return h_;
    }

    public Partner clone()
    {
        Partner c = null;
        try
        {
            c = (Partner)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.rate);
        ostr.writeString(this.scc);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.rate = istr.readString();
        this.scc = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Partner v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Partner ice_read(com.zeroc.Ice.InputStream istr)
    {
        Partner v = new Partner();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Partner> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Partner v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Partner> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Partner.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Partner _nullMarshalValue = new Partner();

    public static final long serialVersionUID = 915045298L;
}
