// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `org.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.thanos.model.svc;

public class Patent implements java.lang.Cloneable,
                               java.io.Serializable
{
    public String publishDate;

    public String name;

    public String applyNo;

    public String publishNo;

    public String category;

    public Patent()
    {
        this.publishDate = "";
        this.name = "";
        this.applyNo = "";
        this.publishNo = "";
        this.category = "";
    }

    public Patent(String publishDate, String name, String applyNo, String publishNo, String category)
    {
        this.publishDate = publishDate;
        this.name = name;
        this.applyNo = applyNo;
        this.publishNo = publishNo;
        this.category = category;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Patent r = null;
        if(rhs instanceof Patent)
        {
            r = (Patent)rhs;
        }

        if(r != null)
        {
            if(this.publishDate != r.publishDate)
            {
                if(this.publishDate == null || r.publishDate == null || !this.publishDate.equals(r.publishDate))
                {
                    return false;
                }
            }
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.applyNo != r.applyNo)
            {
                if(this.applyNo == null || r.applyNo == null || !this.applyNo.equals(r.applyNo))
                {
                    return false;
                }
            }
            if(this.publishNo != r.publishNo)
            {
                if(this.publishNo == null || r.publishNo == null || !this.publishNo.equals(r.publishNo))
                {
                    return false;
                }
            }
            if(this.category != r.category)
            {
                if(this.category == null || r.category == null || !this.category.equals(r.category))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::svc::Patent");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, publishDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, applyNo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, publishNo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, category);
        return h_;
    }

    public Patent clone()
    {
        Patent c = null;
        try
        {
            c = (Patent)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.publishDate);
        ostr.writeString(this.name);
        ostr.writeString(this.applyNo);
        ostr.writeString(this.publishNo);
        ostr.writeString(this.category);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.publishDate = istr.readString();
        this.name = istr.readString();
        this.applyNo = istr.readString();
        this.publishNo = istr.readString();
        this.category = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Patent v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Patent ice_read(com.zeroc.Ice.InputStream istr)
    {
        Patent v = new Patent();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Patent> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Patent v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Patent> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Patent.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Patent _nullMarshalValue = new Patent();

    public static final long serialVersionUID = -1238435641L;
}
